Add tests of fstatfs, epoll_create, epoll_ctl, and epoll_wait yscall in safeposix
Lind-Project/safeposix-rust pull request #182
Opened 2023-07-14 18:30 UTC by Yaxuan-w

## Description

Fixes # (issue)

 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Test A - `lind_project/tests/test_cases/test_a.c`
- Test B - `lind_project/tests/test_cases/test_b.c`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2023-07-14 20:04 UTC, yizhuoliang commented
The fstatfs one is simple and looks good. The epoll one is lengthy yet understandable with the comments. If you still have time, I would recommend trying to register a socket fd that's already closed or doesn't exist, and see if the epoll really complains.

2023-07-14 20:51 UTC, justyoyo123 approved these changes
Both the fstatfs and epoll test are well commented and make sense. Looks good to me.

2023-07-15 09:46 UTC, kuzeyardabulut approved these changes
The comments are very nice and understandable. Looks good to me.

2023-07-15 19:06 UTC, rennergade commented on src/tests/pipe_tests.rs
> +
remove this extra added whitespace

2023-07-15 19:06 UTC, rennergade requested changes
Minor whitespace removal request. Otherwise I think this looks very good. Thanks!

2023-07-19 22:31 UTC, merged