Clearing /tmp on init and finalize
Lind-Project/safeposix-rust pull request #199
Opened 2023-11-09 00:37 UTC by justyoyo123

## Description

Fixes # (issue)

 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Wrote a new test called `ut_lind_fs_tmp_file_test()` in `fs_tests.rs` to verify behavior of `clear_tmp()` function.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2023-11-09 01:56 UTC, RusherRG requested changes
This is a very nice fix and much needed. It will help us a lot while testing out changes without having to clear the filesystem after each test run. Great!

2023-11-09 01:56 UTC, RusherRG commented on src/safeposix/dispatcher.rs
> +    let path = "tmp";
```suggestion
    let path = "/tmp";
```

To be specific.

2023-11-09 01:56 UTC, RusherRG commented on src/safeposix/dispatcher.rs
> +fn cleartmp(flag : bool) {
```suggestion
fn cleartmp(init : bool) {
```

2023-11-09 01:56 UTC, RusherRG commented on src/safeposix/dispatcher.rs
> +        if flag == true {
```suggestion
        if init == true {
```

2023-11-09 01:56 UTC, RusherRG commented on src/safeposix/dispatcher.rs
> +    let path = "tmp";
```suggestion

```

2023-11-09 01:56 UTC, RusherRG commented on src/safeposix/dispatcher.rs
> +    cleartmp(init);
```suggestion
    cleartmp(true);
```
Do we need to create a new variable?

2023-11-10 03:42 UTC, rennergade commented on src/safeposix/dispatcher.rs
> +use crate::lib_fs_utils;
these imports actually should be cleaned up, can you make this just one line?

2023-11-10 20:19 UTC, rennergade approved these changes
looks good, approved!

2023-11-11 23:05 UTC, RusherRG approved these changes

2023-11-13 02:43 UTC, merged