Comments and Tests for sys_calls
Lind-Project/safeposix-rust pull request #270
Opened 2024-06-20 21:59 UTC by Anway-Agte

## Description

Fixes # (issue)
The following changes include the tests and comments in the code for the "get_pid" and "get_ppid" system call under RustPosix.

 

### Type of change

- [ ] This change adds tests and comments to existing code

## How Has This Been Tested?

 

All the tests are inside the ```lind_project/src/safeposix-rust/src/tests/sys_tests/rs``` 

- Test A - `ut_lind_getpid()`
- Test B - `lut_lind_get_ppid()`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2024-06-21 02:32 UTC, rennergade commented on src/tests/sys_tests.rs
> +    pub fn test_fs() {
this should technically be "test_sys" to match the other files syntax

2024-06-21 02:33 UTC, rennergade commented on src/safeposix/syscalls/sys_calls.rs
> +
All of these headers need to be changed to match the RustDoc format. Checkout [this PR](https://github.com/Lind-Project/safeposix-rust/pull/266/files#diff-588741f51e18dec64c5a7299f2caba89320fafeac513840046d6cf3b87064c8b)

and look at the header comments for mkdir and fcntl

2024-06-21 02:36 UTC, rennergade requested changes
Besides the header comments being updated these functions generally need much more comments fleshing out why we do certain steps. Look at the recent PRs that we've merged for examples of what were looking for!

2024-06-22 00:12 UTC, rennergade commented on src/safeposix/syscalls/sys_calls.rs
> +
remove this extra line for this pr

2024-06-22 00:12 UTC, rennergade commented on src/safeposix/syscalls/sys_calls.rs
> +        // Create a new cage object for the child process
remove this comment for this pr

2024-06-22 00:14 UTC, JustinCappos commented on src/safeposix/syscalls/sys_calls.rs
> +    /// Returns a 32 bit default integer (or -1) representing the user
But what we do here is different.  We always return a default number

2024-06-22 00:15 UTC, JustinCappos commented on src/safeposix/syscalls/sys_calls.rs
> +    /// Returns a 32 bit integer value which represents the effective group
Right, but what do we do?

2024-06-22 01:04 UTC, JustinCappos requested changes
A few minor comments, but I'll mark are request changes because I don't understand the test difference.

2024-06-22 01:04 UTC, JustinCappos commented on src/tests/sys_tests.rs
> -        ut_lind_getpid();
Are we intending these changes?

2024-06-22 01:13 UTC, rennergade commented
I think this is a good start. @davidge20 can you give this a review?

2024-06-25 01:04 UTC, rennergade commented on src/safeposix/syscalls/sys_calls.rs
> +        // The call returns -1 to indicate that the call happened during the loading stage
I think a more precise comment here would be:

"We return -1 for the first call for compatibility with the dynamic loader. For subsequent calls we return our default value."

2024-06-25 19:58 UTC, rennergade approved these changes
Looks good! Approved!

2024-06-25 19:58 UTC, merged