Add comments to semaphore
Lind-Project/safeposix-rust pull request #276
Opened 2024-06-24 07:41 UTC by rupeshkoushik07

## Description

Fixes # (issue)
This PR adds comments to semaphore functions

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Test A - `lind_project/tests/test_cases/test_a.c`
- Test B - `lind_project/tests/test_cases/test_b.c`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2024-06-24 12:02 UTC, JustinCappos reviewed
Seems fine.  Should you also have tests which try different permission bits, like "read, not write 0444" or "write, not read 0222"?  

You might also check that the lower order bits are ignored (I assume everyone is the "owner"), so 0600 == 06??...

2024-06-24 15:36 UTC, rennergade commented
> Seems fine. Should you also have tests which try different permission bits, like "read, not write 0444" or "write, not read 0222"?
> 
> You might also check that the lower order bits are ignored (I assume everyone is the "owner"), so 0600 == 06??...

These are specifically semaphore tests so those kind of checks may be better in some new shared memory tests.

2024-06-24 15:38 UTC, rennergade commented
I think these comments are good for the tests. I think there was some miscommunication though because I was hoping you would add comments to the actual semaphore functions in fs_calls

2024-06-25 17:20 UTC, rennergade commented
Thanks Rupesh, @ve1nard can you start this review process off?

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +/// ### Errors and Panics
in alignment with Yash's instructions, the "Errors" and "Panics" sections should be separated. Moreover, please describe cases when the syscall panics.

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
>          // Will initialize only it's new
small typo: should it be "only IF it's new"?

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +/// * `EINVAL (22)`: If the initial value exceeds the maximum allowable value for a semaphore (SEM_VALUE_MAX).
do we support ENOSYS error defined in the standard? If not, please state it

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +/// * `EINVAL (22)`: If the initial value exceeds the maximum allowable value for a semaphore (SEM_VALUE_MAX).
please include a link to the man page of the syscall

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +/// This function initializes a semaphore object, setting its initial value and specifying whether it's shared between threads or processes.
please make sure that the number of character in the comments per line is < 80

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +                    // iterate through all cages with segment attached and add semaphor in segments at attached addr + offset
because you have already inserted the new semaphore into the current initial cage before starting to iterate through the rest of the cages, now when you iterate, is it possible that you get to your initial cage from which the syscall was called and try to insert the semaphor once again? how does it make sure that this does not happen?

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
>                      let offset = mapaddr - sem_handle;
can you please explain the meaning of this offset?

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +/// ### Errors and Panics
please split "Errors and Panics" into two sections

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +/// * `EINVAL(22)`: If the semaphore handle is invalid.
do we support other errors, like EAGAIN or EINTR defined in the standard? if not, please indicate so

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
>              semaphore.lock();
the standard mentions that If the semaphore's value is greater than zero, it is decremented by one, and the semaphore is locked. the decrement part is not clear from the code since it is obscured within the lock method. please make it explicit in the comments

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
>              if !semaphore.unlock() {
from the standard: "If the semaphore's value consequently becomes greater than zero, then another process or thread blocked in sem_wait call will be woken up and proceed to lock the semaphore." Where do we wake up a blocked process/thread here or is it implemented somewhere else? there is a call to `interface::lind_yield()` inside the lock method, but it is not clear how it communicates with the wait call

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
>                                  cage.sem_table.remove(&(addr + offset)); //remove semapoores at attached addresses + the offset
semaphores that other cages are blocked on should not be destroyed. where do you check this?

2024-06-25 20:08 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +/// * `EAGAIN(11)`: If the semaphore is unavailable (its value is 0).
i think specific error descriptions should be placed in the Errors section

2024-06-26 02:54 UTC, rupeshkoushik07 commented
Spot on review, @ve1nard . I'll update them soon.

2024-06-26 14:20 UTC, rupeshkoushik07 commented on src/safeposix/syscalls/fs_calls.rs
> +/// * `EINVAL (22)`: If the initial value exceeds the maximum allowable value for a semaphore (SEM_VALUE_MAX).
Why are we talking about ENOSYS if we're not using it?

2024-06-26 14:20 UTC, rupeshkoushik07 commented on src/safeposix/syscalls/fs_calls.rs
>          // Will initialize only it's new
Its already mentioned below

2024-06-26 14:26 UTC, rupeshkoushik07 commented on src/safeposix/syscalls/fs_calls.rs
>          // Will initialize only it's new
Having it as one statement would definitely make it more concise and clear.

2024-06-26 17:27 UTC, ve1nard commented on src/safeposix/syscalls/fs_calls.rs
> +/// * `EINVAL (22)`: If the initial value exceeds the maximum allowable value for a semaphore (SEM_VALUE_MAX).
this error is defined both in the standard and errnos.rs, so I think it is worth mentioning that such an error is defined, and we just don't support it currently

2024-06-26 19:07 UTC, rupeshkoushik07 commented on src/safeposix/syscalls/fs_calls.rs
> +                    // iterate through all cages with segment attached and add semaphor in segments at attached addr + offset
updated in Description

2024-06-27 10:14 UTC, rupeshkoushik07 commented on src/safeposix/syscalls/fs_calls.rs
>                                  cage.sem_table.remove(&(addr + offset)); //remove semapoores at attached addresses + the offset
I think the sem_destroy_syscall function is called in a context where the semaphore is no longer in use, so the check for blocked cages is unnecessary.

2024-06-27 21:31 UTC, ve1nard approved these changes
All the comments were addressed, so lgtm!

2024-06-27 22:07 UTC, rennergade commented on src/safeposix/syscalls/fs_calls.rs
> +        // Iterate semaphore table, if semaphore is already initialized return error & Will initialize only it's new
This comment isn't really clear, though it definitely wasn't clear from whoever wrote it initially (might be me! oops!) What is actually happening here?

2024-06-27 22:07 UTC, rennergade commented on src/safeposix/syscalls/fs_calls.rs
> +                            // iterate through all cages containing segment
which segment? any segment?

2024-06-27 22:08 UTC, rennergade commented on src/safeposix/syscalls/fs_calls.rs
> +            ///semaphore becomes available. The`lock` method internally decrements the semaphore value.
maybe document where the lock function lives

2024-06-27 22:09 UTC, rennergade commented on src/safeposix/syscalls/fs_calls.rs
> +            // Clone the semaphore entry to avoid modifying the original entry in the table.
I don't think this is actually what is happening with clone here. This is actually dealing with DashMap concurrency so the map isn't blocking.

2024-06-27 22:09 UTC, rennergade commented on src/safeposix/syscalls/fs_calls.rs
> +            // Clone the semaphore entry to avoid modifying the original entry in the table.
same as above

2024-06-27 22:10 UTC, rennergade commented on src/safeposix/syscalls/fs_calls.rs
> +            // Clone the semaphore entry to avoid modifying the original entry in the table.
same

2024-06-27 22:11 UTC, rennergade requested changes
Some of the comments are a bit surface level where I follow what each individual line is doing but am not sure what the goals are of a greater block of code. If you could add a comment to the top of larger blocks explaining what is going to happen that could be a lot clearer.

2024-06-28 16:46 UTC, rennergade approved these changes
Looks great. Thanks Rupesh. Approved.

2024-06-28 16:46 UTC, merged