getcwd_syscall() updates
Lind-Project/safeposix-rust pull request #280
Opened 2024-06-27 18:16 UTC by ve1nard

## Description

Fixes # (issue)

The following changes include a small fix for checking null pointers, more elaborate comments, and new unit tests for `getcwd_syscall()`.

### Type of change

- [ ] More detailed comments for `getcwd_syscall()`
- [ ] Added a condition to error-out null pointers passed as `buf` argument
- [ ] New unit tests for `getcwd_syscall()`

## How Has This Been Tested?

To run the tests, we need to run cargo test --lib command inside the safeposix-rust directory.

All the tests are present under this directory: lind_project/src/safeposix-rust/src/tests/fs_tests.rs

- Test A - `lut_lind_fs_getcwd_valid_args()`
- Test B - `ut_lind_fs_getcwd_invalid_args()`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2024-06-27 21:17 UTC, rennergade commented
@Anway-Agte can you review this before Rupesh does?

2024-06-30 00:11 UTC, Anway-Agte requested changes

2024-06-30 00:11 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +    pub fn ut_lind_fs_fcntl_dup() {
Are these changes intentional?

2024-06-30 00:11 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +        //and changing to it
small typo - think it should be "Exists"

2024-06-30 00:11 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +        //current woring directory `/newcwd1`
small typo - "working"

2024-06-30 00:11 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +        //Creating the new current working directory and checking if it exits
small typo - i think this should be "exists"

2024-06-30 18:35 UTC, ve1nard commented on src/tests/fs_tests.rs
> +    pub fn ut_lind_fs_fcntl_dup() {
this is the result of running cargofmt

2024-07-01 03:26 UTC, Anway-Agte approved these changes

2024-07-01 03:26 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +        //and also performs clean env setup
It'd be good if you can explain in a couple of lines what happens in the clean env setup

2024-07-01 03:26 UTC, Anway-Agte commented on src/tests/fs_tests.rs
>          assert_eq!(std::str::from_utf8(&buf).unwrap(), "/\0\0\0\0\0\0\0\0");
Why are there multiple null terminators in the string that represents the root directory?

2024-07-01 03:26 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +        //than the size of the current working direcotry plus the terminating null
"directory"

2024-07-01 03:26 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +        assert_eq!(cage.getcwd_syscall(bufptr, 0), -(Errno::EINVAL as i32));
why do we negate the sign of the error number?

2024-07-01 03:26 UTC, Anway-Agte commented on src/tests/fs_tests.rs
In this function - do we also need to check if the getcwd syscall handles the case when the pointer passed to it is not a pointer to a string but a different variable?

2024-07-01 15:47 UTC, ve1nard commented on src/tests/fs_tests.rs
>          assert_eq!(std::str::from_utf8(&buf).unwrap(), "/\0\0\0\0\0\0\0\0");
the root directory is represented by "/". everything else is just to fill up the remaining space for the sake of the example

2024-07-01 16:00 UTC, rupeshkoushik07 approved these changes
looks good to me!

2024-07-01 23:07 UTC, rennergade commented on src/safeposix/syscalls/fs_calls.rs
> +        if !buf.is_null() {
I see why you added this but its actually redundant. We do any checks for EFAULT in the type checker as well as within the actual runtime. I'd remove this check and note that its checked in types.rs.

2024-07-01 23:08 UTC, rennergade requested changes
Minor comment about the EFAULT check. I also don't really know why there are so many extra files in this PR.

Otherwise really great job on this one, incredibly thorough.

2024-07-02 00:00 UTC, rennergade approved these changes
Awesome. Great job!

2024-07-02 00:00 UTC, merged