Writev syscall comments and tests
Lind-Project/safeposix-rust pull request #291
Opened 2024-07-07 15:23 UTC by rupeshkoushik07

## Description
This PR adds description and tests to writev syscall.
Fixes # (issue)

 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Test A - `lind_project/tests/test_cases/test_a.c`
- Test B - `lind_project/tests/test_cases/test_b.c`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2024-07-07 22:59 UTC, Anway-Agte commented on src/safeposix/syscalls/fs_calls.rs
>                              IPPROTO_TCP => {
Could you add more comments - because the part after line 1895 seems a bit confusing

2024-07-07 22:59 UTC, Anway-Agte commented on src/safeposix/syscalls/fs_calls.rs
> +    /// * `iovec`: A pointer to an array of `IovecStruct` objects representing the data buffers to write.
What is a IovecStruct?

2024-07-07 22:59 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +        let mut socketpair = interface::SockPair::default();
Can you add a couple of comments explaining why we do this?

2024-07-22 15:45 UTC, Anway-Agte approved these changes

2024-07-22 15:45 UTC, Anway-Agte commented on src/tests/fs_tests.rs
> +        // Prepare the data to be written using an iovec structure
This part seems redundant in both the socketpair and pipe test functions - can this not be abstracted out into a single function that takes a file descriptor and runs the tests on that fd?

2024-07-22 20:01 UTC, namanlalitnyu requested changes
A couple of minor comments.

2024-07-22 20:01 UTC, namanlalitnyu commented on src/safeposix/syscalls/fs_calls.rs
> +    /// ### Panics
Just to maintain consistency with other syscalls, we can add extra line before and after "Panics" section.

2024-07-22 20:01 UTC, namanlalitnyu commented on src/safeposix/syscalls/fs_calls.rs
>                      if pipe_filedesc_obj.flags & O_NONBLOCK != 0 {
Explaining a bit about why we are writing in non-blocking mode would be great.

2024-07-22 20:01 UTC, namanlalitnyu commented on src/tests/fs_tests.rs
> +    use crate::tests::FileDescriptor::Socket;
Shouldn't we move the imports above to the top of the file with the existing ones?

2024-07-22 20:01 UTC, namanlalitnyu commented on src/tests/fs_tests.rs
> +        // Verify that the data
I think this sentence is incomplete here.

2024-07-26 18:06 UTC, namanlalitnyu approved these changes

2024-07-27 21:07 UTC, rupeshkoushik07 commented on src/tests/fs_tests.rs
> +        // Prepare the data to be written using an iovec structure
I think we may not need helper functions in test cases.

2024-08-23 06:41 UTC, closed without merging