mmap_syscall() and munmap_syscall() updates
Lind-Project/safeposix-rust pull request #300
Opened 2024-07-11 21:22 UTC by ve1nard

## Description

Fixes # (issue)

The following changes include more elaborate comments and new unit tests for `mmap_syscall()` and `munmap_syscall()`.

### Type of change

- [ ] More detailed comments for `mmap_syscall()` and `munmap_syscall()`
- [ ] New unit tests for `mmap_syscall()` and `munmap_syscall()`

## How Has This Been Tested?

To run the tests, we need to run cargo test --lib command inside the safeposix-rust directory.

All the tests are present under this directory: lind_project/src/safeposix-rust/src/tests/fs_tests.rs

- Test A - `lut_lind_fs_mmap_zerolen()`
- Test B - `ut_lind_fs_mmap_invalid_flags_none()`
- Test C - `ut_lind_fs_mmap_invalid_flags_both()`
- Test D - `ut_lind_fs_mmap_no_read()`
- Test E - `ut_lind_fs_mmap_no_write()`
- Test F - `ut_lind_fs_mmap_invalid_offset_len()`
- Test G - `ut_lind_fs_mmap_chardev()`
- Test H - `ut_lind_fs_mmap_unsupported_file()`
- Test I - `ut_lind_fs_mmap_invalid_fildes()`
- Test J - `ut_lind_fs_munmap_zerolen()`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2024-07-13 00:55 UTC, namanlalitnyu reviewed
Few minor changes, but looks good overall!

2024-07-13 00:55 UTC, namanlalitnyu commented on src/safeposix/syscalls/fs_calls.rs
> +    ///   and new file descriptors would point to the same file description.
Can you take the latest pull for develop, I think these changes should disappear from it.

2024-07-13 00:55 UTC, namanlalitnyu commented on src/safeposix/syscalls/fs_calls.rs
>                          Inode::CharDev(_chardev_inode_obj) => {
We can move this up the order to fail early.

2024-07-13 00:55 UTC, namanlalitnyu commented on src/safeposix/syscalls/fs_calls.rs
> +    /// * `EINVAL` - the value of len is 0 o
minor - extra o.

2024-07-13 00:55 UTC, namanlalitnyu commented on src/tests/fs_tests.rs
> +        lindrustfinalize();
Can you check with the tests for other cases of `munmap`, where we unmap a valid memory address space for a process?

2024-07-13 23:43 UTC, namanlalitnyu approved these changes
LGTM!

2024-07-14 23:16 UTC, rennergade commented on src/safeposix/syscalls/fs_calls.rs
> +                            //The actual memory mapping is not emulated inside Lind, so the call to the kernell
kernel

2024-07-14 23:17 UTC, rennergade requested changes
this looks really good only had a minor revision

2024-07-15 02:17 UTC, rennergade approved these changes

2024-07-15 02:17 UTC, merged