Update write vectored
Lind-Project/safeposix-rust pull request #323
Opened 2024-08-23 06:39 UTC by rupeshkoushik07

## Description

- Adds comments and tests to writev_syscall
- Adds stream functionality to writev_syscall
- Update write_vectored_to_pipe 

Fixes # (issue)

 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Test A - `lind_project/tests/test_cases/test_a.c`
- Test B - `lind_project/tests/test_cases/test_b.c`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

2024-08-26 17:22 UTC, rennergade commented on src/interface/file.rs
> +            total_bytes_written = file.write_vectored(bufs)?;
You should be able to use "write_vectored_at" here instead of seeking and using write_vectored

2024-08-26 17:23 UTC, rennergade commented on src/interface/misc.rs
> +                1 => {
at this point we only log things to stdout so you shouldn't differentiate here.

2024-08-26 17:25 UTC, rennergade commented on src/tests/fs_tests.rs
> +        let data = b"Hello, pipe!";
Lets make this a bit more complex of an iovec and test some other situations

2024-08-26 17:26 UTC, rennergade requested changes
This is mostly great. I think the testing should be a bit more robust. Would like a file writev test added as well.

2024-09-03 04:01 UTC, rennergade approved these changes

2024-09-03 04:02 UTC, rennergade commented
I think this looks good but its failing tests, I think due to you adding write_vectored_at to lib.rs. I know you have to do that but its causing some issue with the runner. @yashaswi2000 can you also give this a review and look at why the test is failing?

2024-09-03 04:12 UTC, yashaswi2000 commented
the build itself is failing, @rupeshkoushik07 are you able to run cargo test on your local?

2024-09-03 12:39 UTC, rupeshkoushik07 commented
@yashaswi2000 Even after adding `#![feature(unix_file_vectored_at)]` to `lib.rs`, I still encounter the same error locally.

2024-09-03 19:08 UTC, yashaswi2000 approved these changes
LGTM

2024-09-03 19:11 UTC, merged